
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: tenpo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54320:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build: .
    container_name: tenpo-app
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/tenpo_db
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge