spring:
  application:
    name: tenpo

  r2dbc:
    url: r2dbc:postgresql://localhost:54320/tenpo_db
    username: user
    password: password
  sql:
    init:
      mode: always

  data:
    redis:
      port: 6379
      host: redis
  cache:
    type: redis
    redis:
      host: redis
      port: 6379
      password: ''
      database: 0
      time-to-live: 1800s

resilience4j.retry:
  instances:
    externalPercentageServiceRetry:
      maxAttempts: 3
      waitDuration: 1000ms
      enableExponentialBackoff: false


springdoc:
  swagger-ui:
    enabled: true


